### ISSUE TITLE
Ctrl-C

### ISSUE THREAD

**Issue by ckirsch** [cksystemsteaching/selfie#144]
Pressing Ctrl-C just once should terminate grader.

**Comment by ChristianMoesl** [comment]
I will look into that at the weekend

**Comment by Blazefrost** [comment]
I could not reproduce this issue for any of the assignments on the current repository. It _should_ already be handled by commit 9ef29054, but it seems to be older than the issue.

Does this bug affect the bulk grader, by chance? I couldn't test it yet.

**Comment by ckirsch** [comment]
@ChristianMoesl I don't remember, please see @Blazefrost comments.

**Comment by ChristianMoesl** [comment]
@ckirsch I also think, that it already has been fixed. But also if there is a problem, it's probably in the bulk grader.

**Comment by ckirsch** [comment]
Ok, I close this for now.

**Comment by Blazefrost** [comment]
@fischer-martin notified me that this issue is still present for the bulk grader. Currently, you have to press [Ctrl]+[C] as often as there are repositories left to process.

**Comment by fischer-martin** [comment]
To be exact: I think the bug only happens if no assignment has been specified (i.e. running `./self.py -b commit-links.txt -d student-repos`).
